Func templates
semen603089/dyakov-api-for-fkn pull request #2
Opened 2022-05-24 20:45 UTC by semen603089

2022-05-26 15:11 UTC, dyakovri commented on dbengine/branch.py
> +        branch.type = BranchTypes.MERGED
В статус MR должно переходить

2022-05-26 15:18 UTC, dyakovri commented on dbengine/table.py
> +        raise ProhibitedActionInBranch("Deleting table", branch.name)
На таких штуках обычно делают так:

```python
if branch.type == BranchTypes.MAIN:
    raise ProhibitedActionInBranch("Deleting table", branch.name)
    
s = session.query(Commit).filter(Commit.branch_id == table.id).order_by(Commit.id.desc()).first()
new_commit = Commit()
new_commit.attribute_id_in = table.id
if s:
    new_commit.prev_commit_id = s.prev_commit_id + 1
new_commit.attribute_id_out = None
new_commit.branch_id = branch.id
session.add(new_commit)
session.flush()
session.commit()
```
То есть сначала обрабатывают один ошибочный случай, а потом в общем потоке работают без элза. Уменьшает вложенность и упрощает чтение кода

2022-05-26 15:21 UTC, dyakovri requested changes
Помимо комментариев в коде, кажется, будто очень много коммитов в БД. Обычно хватает делать флаш без коммита, а коммит только один в конце функции.

2022-05-26 15:21 UTC, dyakovri commented on dbengine/branch.py
> +        branch.type = BranchTypes.MERGED
Статус должен быть MR

2022-05-27 11:12 UTC, dyakovri commented
Еще правки:
- Изменения в ветках со статусом != WIP запрещены
- В update_column мы требуем объект DBColumn, который уже привязан к таблице, не надо таблицу запрашивать еще раз

2022-05-27 11:16 UTC, dyakovri commented
update_column  и update_table не создают новые колонку и таблицу, они должны изменять атрибуты существующих

2022-05-28 01:48 UTC, semen603089 commented
fix get_table MultipleResultsFound exc

2022-05-30 00:42 UTC, semen603089 commented
10/10 tests

2022-05-30 01:03 UTC, dyakovri commented on dbengine/table.py
> +        logging.error(AttributeError, exc_info=True)
Что не так с атрибутами и почему мы их можем просто игнорировать? Может стоит таки выплевывать ошибку?
Ну и вывод в данном случае не соответствует описанию функции

2022-05-30 01:03 UTC, dyakovri commented on dbengine/table.py
> +        logging.error(AttributeError, exc_info=True)
Что не так с атрибутами и почему мы их можем просто игнорировать? Может стоит таки выплевывать ошибку?
Ну и вывод в данном случае не соответствует описанию функции

2022-05-30 01:03 UTC, dyakovri commented on dbengine/table.py
> +            delete_column(branch, row, session=session)
Кажется логичным сначала удалить столбцы из таблицы, а потом удалить таблицу

2022-05-31 03:37 UTC, merged